version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/loader"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/loader"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
