#!/bin/bash
set -euo pipefail

SERVER_DEPLOY_TFJSON_PATH=terraform/server_deploy.tf.json

require_clean_work_tree () {
    # from git-sh-setup.sh: https://www.spinics.net/lists/git/msg142043.html

    # Update the index
    git update-index -q --ignore-submodules --refresh
    err=0

    # Disallow unstaged changes in the working tree
    if ! git diff-files --quiet --ignore-submodules --
    then
        echo >&2 "cannot $0: you have unstaged changes."
        git diff-files --name-status -r --ignore-submodules -- >&2
        err=1
    fi

    # Disallow uncommitted changes in the index
    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
    then
        echo >&2 "cannot $0: your index contains uncommitted changes."
        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
        err=1
    fi

    if [ $err = 1 ]
    then
        echo >&2 "Please commit or stash them."
        exit 1
    fi
}
require_clean_work_tree;

cd "$(git rev-parse --show-toplevel)"

NEXT_REV=$(git rev-parse HEAD)

cat << EOF > "$SERVER_DEPLOY_TFJSON_PATH"
{
  "//": "This file is generated by server/scripts/deploy.sh. DO NOT HAND-EDIT!",

  "variable": {
    "api_release_version": {
      "description": "API Release Version",
      "default": "$NEXT_REV"
    }
  }
}
EOF

git add "$SERVER_DEPLOY_TFJSON_PATH"
git commit -m "Deploy server version $NEXT_REV"

