on:
  pull_request: {}
  push:
    branches:
      - main

name: Continuous Integration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-v1-${{ hashFiles('server/package-lock.json', 'loader/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v1
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          cd server
          npm ci
          cd ../loader
          npm ci

      - name: Run server tests
        run: |
          cd server
          npm run test

      - name: Run loader tests
        run: |
          cd loader
          npm run test

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-v1-${{ hashFiles('server/package-lock.json', 'loader/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v1
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          cd server
          npm ci
          cd ../loader
          npm ci

      - name: Lint Server
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: server/
          prettier: true
          prettier_dir: server/

      - name: Lint Loader
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: loader/
          prettier: true
          prettier_dir: loader/

  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml", ".github/workflows/*.yml"]'
