on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "terraform/**"
      - "render.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "terraform/**"
      - "docker/postgis/**"

name: Continuous Integration

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # PostGIS service for use with server tests
      postgres:
        image: "postgis/postgis:13-3.1"
        env:
          POSTGRES_DB: univaf-test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test-password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          npm ci

      - name: Run common tests
        if: ${{ always() }}
        env:
          NOCK_BACK_MODE: lockdown
        run: |
          npm run test --workspace common

      # A build version of common will be needed for loader/server tests.
      - name: Build common package
        if: ${{ always() }}
        run: |
          npm run build --workspace common

      - name: Run server tests
        if: ${{ always() }}
        run: |
          npm run test --workspace server
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: test
          DB_NAME: univaf
          DB_PASSWORD: test-password

      - name: Run loader tests
        if: ${{ always() }}
        env:
          NOCK_BACK_MODE: lockdown
        run: |
          npm run test --workspace loader

      # TODO: We should write some tests :(
      - name: Build UI
        if: ${{ always() }}
        run: |
          cd ui
          NODE_ENV=production npm run build

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-npm-v2-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-v2
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          npm ci

      # We have ESLint and Prettier installed separately in each subproject,
      # but this action can only run once per job. So we run the versions
      # installed in the server project on both at once, and have some weird
      # arguments.
      - name: Lint JS Code
        if: github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: js,ts
          prettier: true

      - name: Lint JS Code (without GitHub checks)
        if: github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name != github.repository
        run: |
          npx eslint --ext 'js,ts' .
          echo "--------------------------------------------------------------"
          echo "Prettier:"
          npx prettier --check .

  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow files
        run: |
          # Install actionlint
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          # Install matcher for GitHub line annotations
          curl 'https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json' > actionlint-matcher.json
          echo "::add-matcher::./actionlint-matcher.json"

          ./actionlint

  build_docker:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Instead of building all combinations of a set of options, just build
        # these particular combinations.
        include:
          - repository: univaf-server
            target: server
            dockerfile: "./server/Dockerfile"
            build_path: "./server"

          - repository: univaf-loader
            target: loader
            dockerfile: "./loader/Dockerfile"
            build_path: "./loader"
    env:
      ECR_REPOSITORY: ${{ matrix.repository }}
      IMAGE_TAG: ${{ github.sha }}
      IMAGE_NAME: "dev/${{ matrix.repository }}:${{ github.sha }}"
    steps:
      - uses: actions/checkout@v3

      # The docker action should have the ability to cache directly to the
      # GitHub Actions cache without an explicit cache action like this, but we
      # have not been able to get it to work.
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # Use the commit SHA in the key since there's no file that makes sense
          # to hash for a unique key.
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-

      - name: Inspect Incoming Cache
        run: |
          ls -lah /tmp/.buildx-cache
          cat /tmp/.buildx-cache/index.json | jq
          ls -lah /tmp/.buildx-cache/blobs/sha256

      # Sets up a docker driver that supports caching.
      - name: Set up Docker Buildx
        id: buildx-setup
        uses: docker/setup-buildx-action@v2
        with:
          # install: true
          buildkitd-flags: --debug

      - name: Build ${{ matrix.repository }}
        uses: docker/build-push-action@v3
        with:
          context: "."
          tags: "${{ env.IMAGE_NAME }}"
          target: "${{ matrix.target }}"
          build-args: |
            RELEASE=${{ env.IMAGE_TAG }}
          # builder: "${{ steps.buildx-setup.outputs.name }}"
          # The caching mechanism will add a new copy of the cache to the
          # destination directory, so we write the cache out to a new, clean
          # directory and then overwrite the old cache directory with it after.
          # (See next action.)
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache-new,mode=max,compression=zstd"
          push: false
          # Make the image available to Docker CLI commands in the next steps.
          load: true

      - name: Overwrite Old Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Inspect Outgoing Cache
        run: |
          ls -lah /tmp/.buildx-cache
          cat /tmp/.buildx-cache/index.json | jq
          ls -lah /tmp/.buildx-cache/blobs/sha256

      - name: Report Image Details
        run: |
          SIZE=$(
            docker image inspect \
              --format '{{ .VirtualSize }}' \
              "${IMAGE_NAME}"
          )
          SIZE_MB=$((SIZE / 1024 / 1024))
          echo "Built image \`${IMAGE_NAME}\`: ${SIZE_MB} MB" >> "$GITHUB_STEP_SUMMARY"

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        if: github.ref == 'refs/heads/main'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag and push ${{ matrix.repository }} latest
        if: github.ref == 'refs/heads/main'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          PUBLISH_NAME="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker tag "${IMAGE_NAME}" "${PUBLISH_NAME}"
          docker push "${PUBLISH_NAME}"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - build_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create + push deploy commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@usdigitalresponse.org"

          ./scripts/deploy_infra.sh
          git push
